{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tigateway.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "tigateway.labels" . | nindent 4 }}
{{- end }}
