apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "tigateway.fullname" .) }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "tigateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.gateway }}
    targetPort: 8080
    protocol: TCP
    name: http
  - port: {{ .Values.service.ports.admin }}
    targetPort: 8081
    protocol: TCP
    name: admin
  - port: {{ .Values.service.ports.management }}
    targetPort: 8090
    protocol: TCP
    name: management
  selector:
    {{- include "tigateway.selectorLabels" . | nindent 4 }}
{{- if and (eq .Values.service.type "LoadBalancer") .Values.ingress.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "tigateway.fullname" .) }}-lb
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "tigateway.labels" . | nindent 4 }}
    service-type: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    {{- include "tigateway.selectorLabels" . | nindent 4 }}
{{- end }}
